name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: lean-action
        name: build, test, and lint project
        uses: leanprover/lean-action@v1
        with:
          build-args: '--wfail'
